### PR TITLE
Add visibility attribute for GCC and Clang + Add guard macros

### PR DESCRIPTION
**Pull request by andyvand**
Add visibility attribute for GCC and Clang + Add guard macros
Fix for modern compilers.
Add building of shared library option (BUILD_SHARED=ON).
Fix check to check for WIN32 and _WIN32
Fix for newer and older MSVC compilers (check for _MSC_VER and __STDC_WANT_SECURE_LIB__ so it doesn't #define *_s in case of newer MSVC compiler).

### CODE REVIEW

**Comment by nikitalita** [comment]
Does opentyrian officially support these old OSes and compilers? I would otherwise be disinclined to take the commits that rollback the later C++ features.

**Comment by andyvand** [comment]
> Does opentyrian officially support these old OSes and compilers? I would otherwise be disinclined to take the commits that rollback the later C++ features.

Yes I have Mac OS X 10.5 working 
These old compilers support SDL2 with patches.
I am compiling an appropriate version.

**Comment by andyvand** [comment]
I have built OpenTyrian2000 with MIDI support succesfully for Mac OS X 10.5.

Release page:
https://github.com/andyvand/opentyrian2000/releases/tag/2.2.0-MIDI

I have also created an application to convert music.mus to musicX.mid.

Files:
https://github.com/andyvand/opentyrian2000/tree/master/extras

I have tested this using the sdl_test.
Scherm­afbeelding 2024-07-10 om 18 31 07

Also made conversion from .mid to .mp3

The result is here:
opentyrian2000-OSX10 5

**Comment by nikitalita** [comment]
It looks good to me, but I should warn you: if the objective is to add support for old PowerPC Macs, that would require a *ton* of refactoring, as PowerPC is big-endian and nearly all the music formats we support are stored little-endian.

**Comment by andyvand** [comment]
I have created an extra branch and reverted the code.
I have made some fixes to it.
oldos branch has the modified code for Mac OS X 10.5
You can make and merge the branch.
main branch has the new features intact.
oldos branch has the code for legacy compilers (GCC 3 and better)

**Comment by nikitalita** [comment]
Yeah, I think that would be your best bet, as there's no guarantee that this won't get updated in a way that's compatible with ancient compilers and break something. Thank you for all of your work on this!

**Pull request merged**
